FROM php:8.5-fpm

RUN docker-php-ext-install pdo pdo_mysql

RUN apt-get update && apt-get install -y \
   zip unzip git \
   && rm -rf /var/lib/apt/lists/*

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www
COPY ./composer.json /var/www/composer.json
COPY ./composer.lock /var/www/composer.lock

CMD ["php-fpm"]
