on:
  push:
    branches:
      - web

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lab9

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Create .env
        run: |
          touch .env
          echo "MYSQL_ROOT_PASSWORD=${{secrets.MYSQL_ROOT_PASSWORD}}" >> .env
          echo "MYSQL_DATABASE=${{secrets.MYSQL_DATABASE}}" >> .env
          echo "MYSQL_USER=${{secrets.MYSQL_USER}}" >> .env
          echo "MYSQL_PASSWORD=${{secrets.MYSQL_PASSWORD}}" >> .env
          echo "MYSQL_HOST=${{secrets.MYSQL_HOST}}" >> .env

      - name: Start docker
        run: docker compose up -d --build

      - name: Install dependencies
        run: php composer install

      - name: Run tests
        run: php vendor/bin/phpunit tests/

      - name: Stop containers
        if: always()
        run: docker compose down

